# Numpy Library In Python


In [4]:
#Import library of numpy
import numpy as np

#### Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type.

In [5]:
# Integer Array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
# We can set the data type by ourself
np.array([1,2,3,4,5] , dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
# Creating Array from Scratch
# Zero nparrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Creat ( 3 by 5 ) array filled with 1s
np.ones((3,5 ) , dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Creat ( 3 by 5 ) array filled with 10
numpy_list = np.full((3,5) , 10 )
numpy_list

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

#### - Dimension of Array

In [16]:
# Check the demintion of array
np.ndim(numpy_list)

2

In [17]:
# Creat a list start from 0 and ends at 10 with differnce of 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
# Creat an array of 5 values evenly space between 0 and 2
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
# Creat (3 by 3) array of random numbers between 0 and 1
np.random.random((3, 3))

array([[0.31924741, 0.05175494, 0.02879604],
       [0.35031918, 0.70664903, 0.31829404],
       [0.18410577, 0.30618125, 0.01615729]])

In [26]:
# Creat (3 by 3) array of random numbers between 0 and 10
np.random.randint(0,10,(3, 3))

array([[2, 3, 0],
       [1, 0, 3],
       [6, 1, 0]])

In [29]:
# creat empty array for memory location
np.empty((3,3))

array([[0.7268053 , 0.09468512, 0.12986413],
       [0.55932334, 0.07507298, 0.37023327],
       [0.05391215, 0.86062074, 0.21880296]])

In [37]:
# Checking array size , array deminsion , array shape (no of rows , no of colums) , datatype of array
array = np.random.randint(0,50,(5,5))
print("The Dimention of this array is ",  array.ndim)
print("The Size of this array is ",  array.size)
print("The Shape of this array is ",  array.shape)
print("The data type of this array is ",  array.dtype)

The Dimention of this array is  2
The Size of this array is  25
The Shape of this array is  (5, 5)
The data type of this array is  int32


#### Array indexing

In [43]:
# Lets creat a list of first 10 whole numbers
L = np.arange(10)
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# Array & list Indexing
L[2]

2

In [47]:
# end of array index is -1 , the last index of array can be index as -1
L[-1]

9

In [50]:
#Replacing element of array by indexing array
L[2] = 22
L

array([ 0,  1, 22,  3,  4,  5,  6,  7,  8,  9])

In [57]:
# Lets creat another array
L1 = np.random.randint(0,10,(3, 3))
L1

array([[8, 3, 7],
       [4, 6, 4],
       [8, 2, 0]])

In [62]:
# Selecting by index
L1[0,1]

3

#### Slicing of Array

In [64]:
# Slicing a array by rows and coloums
L1[0:2]

array([[8, 3, 7],
       [4, 6, 4]])

In [66]:
L1[1:3]

array([[4, 6, 4],
       [8, 2, 0]])

In [70]:
# Selecting ros and colums
L1[0:3,2:3]

array([[7],
       [4],
       [0]])

In [72]:
# Reversing all the list 
L1[::-1]

array([[8, 2, 0],
       [4, 6, 4],
       [8, 3, 7]])

In [74]:
# Another way to reverse the array is transpose
L1.T

array([[8, 4, 8],
       [3, 6, 2],
       [7, 4, 0]])

In [91]:
# Copying an array for later use or any specifice use
L1_copy = L1.copy()
L1_copy

array([[8, 3, 7],
       [4, 6, 4],
       [8, 2, 0]])

In [95]:
L1_copy = L1_copy[0:2]
L1_copy

array([[8, 3, 7],
       [4, 6, 4]])

In [109]:
# Creat ana array of 9 int and then reshape
reshape_array = np.arange(9)
reshape_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
# Reshaping an array
reshape_array.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Array Concatenation

In [133]:
# concatenate 2 or more array into 1
a1 = np.arange(5)
print('a1 ::',a1)
a2 = np.arange(5,10)
print('a2 ::',a2)
con = np.concatenate([a1,a2])
print(con)

a1 :: [0 1 2 3 4]
a2 :: [5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [149]:
# concatenate Multidementional  array into 1
print('L1 shape is  ::',L1.shape)
print('L1_copy shape is  ::',L1_copy.shape)
print('Lets Concatenate L1 and L1_copy')
con = np.concatenate([L1,L1_copy])
print('Now the shape of concatenated arry is ', con.shape)
print(con)


L1 shape is  :: (3, 3)
L1_copy shape is  :: (2, 3)
Lets Concatenate L1 and L1_copy
Now the shape of concatenated arry is  (5, 3)
[[8 3 7]
 [4 6 4]
 [8 2 0]
 [8 3 7]
 [4 6 4]]


#### Splitting of Array

In [152]:
# Splitting of arrays 'The opposite of concatenation is splitting'
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [166]:
grid = np.arange(16).reshape((4, 4))
print(grid)
print('___________________')
# Spliting the array in uper and lower numbers

upper, lower = np.vsplit(grid, [2])
print('Spliting Upper')
print(upper)

print('___________________')

print('Spliting Lower')
print(lower)

print('___________________')
left, right = np.hsplit(grid, [2])
print('Spliting Left')
print(left)

print('___________________')
print('Spliting Right')
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
___________________
Spliting Upper
[[0 1 2 3]
 [4 5 6 7]]
___________________
Spliting Lower
[[ 8  9 10 11]
 [12 13 14 15]]
___________________
Spliting Left
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
___________________
Spliting Right
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
